import {useState} from 'react';
import {ArrowUpRight,Plus,Minus,CalendarDays,MessageCircle} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {bookingUrl,whatsappNumber} from '../data/content';
export default function BookingPlanner({lang='es'}:{lang?:string}) {
 const en=lang==='en';const [adults,setAdults]=useState(2);const [children,setChildren]=useState(0);const [date,setDate]=useState('');
 const today=new Intl.DateTimeFormat('sv-SE',{timeZone:'Europe/Madrid'}).format(new Date());
 const dateOk=!date||date>=today;
 const message=en?`Hello Sidra Kane! I would like to enquire about a visit for ${adults} paying visitors and ${children} children up to 12${date?' on '+date:''}. Could you confirm availability and the price? Thank you!`:`¡Hola, Sidra Kane! Me gustaría consultar una visita para ${adults} personas de pago y ${children} niños hasta 12 años${date?' el '+date:''}. ¿Podéis confirmarme disponibilidad y precio? ¡Gracias!`;
 return <div className="planner"><p className="eyebrow">{en?'VISIT & CIDER TASTING':'VISITA Y CATA DE SIDRA'}</p><h3>{en?'Book your visit.':'Reserva tu visita.'}</h3><p className="planner-intro">{en?'Estate tour, history, cider tasting and seasonal local produce.':'Recorrido por el caserío, historia de la sidra y cata con producto local de temporada.'}</p><div className="planner-price"><span>30 €</span><small>{en?'per person':'por persona'}<br/>90 {en?'minutes':'minutos'}</small></div>
 <div className="counter-row"><label id="adults-label">{en?'Paying visitors':'Personas de pago'}<small>{en?'Ages 13 and over':'Desde 13 años'}</small></label><div className="counter"><Button variant="ghost" size="icon" onClick={()=>setAdults(Math.max(1,adults-1))} disabled={adults<=1} aria-label={en?'Remove one paying visitor':'Quitar una persona de pago'}><Minus size={15}/></Button><output aria-labelledby="adults-label" aria-live="polite">{adults}</output><Button variant="ghost" size="icon" onClick={()=>setAdults(adults+1)} aria-label={en?'Add one paying visitor':'Añadir una persona de pago'}><Plus size={15}/></Button></div></div>
 <div className="counter-row"><label id="children-label">{en?'Children':'Niños'}<small>{en?'Up to 12 · free':'Hasta 12 años · gratis'}</small></label><div className="counter"><Button variant="ghost" size="icon" onClick={()=>setChildren(Math.max(0,children-1))} disabled={children<=0} aria-label={en?'Remove one child':'Quitar un niño'}><Minus size={15}/></Button><output aria-labelledby="children-label" aria-live="polite">{children}</output><Button variant="ghost" size="icon" onClick={()=>setChildren(children+1)} aria-label={en?'Add one child':'Añadir un niño'}><Plus size={15}/></Button></div></div>
 <div className="planner-total" aria-live="polite"><span>{en?'Estimated total':'Total orientativo'}</span><strong>{adults*30} €</strong></div><p className="planner-small">{en?'Standard visit price. Group and special-activity rates are confirmed by the team.':'Precio de la visita estándar. El equipo confirma tarifas de grupos y actividades especiales.'}</p>
 <a className="button" href={bookingUrl} target="_blank" rel="noopener noreferrer"><CalendarDays size={17}/>{en?'Check availability':'Consultar disponibilidad'}<ArrowUpRight size={18}/></a><p className="planner-small calendar-note">{en?'Opens Kane’s calendar to choose a time and book.':'Abre el calendario de Kane para elegir horario y reservar.'}</p>
 <div className="planner-whatsapp"><label htmlFor="preferred-date">{en?'Preferred date for your enquiry (optional)':'Fecha para tu consulta (opcional)'}</label><Input type="date" id="preferred-date" min={today} value={date} onChange={e=>setDate(e.target.value)} aria-invalid={!dateOk} aria-describedby={!dateOk?'date-error':undefined} className="date-input"/>{!dateOk&&<p id="date-error" role="alert">{en?'Choose today or a future date.':'Elige hoy o una fecha futura.'}</p>}
 {dateOk?<a className="whatsapp-link" href={`https://wa.me/${whatsappNumber}?text=${encodeURIComponent(message)}`} target="_blank" rel="noopener noreferrer"><MessageCircle size={17}/>{en?'Ask via WhatsApp':'Consultar por WhatsApp'}<ArrowUpRight size={16}/></a>:<span className="whatsapp-link" aria-disabled="true">{en?'Choose a valid date to enquire':'Elige una fecha válida para consultar'}</span>}<p className="planner-small">{en?'You send the message. Your visit is booked only when Kane confirms it.':'Tú envías el mensaje. La visita queda reservada cuando Kane la confirma.'}</p></div>
 </div>;
}
